In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
data = pd.read_csv('dataset.csv',encoding='cp949')

In [3]:
data.head()

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
0,378508,378475,508475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,378509,378475,509475,2021-01-01,0.00,0.00,0.4,0.00,0.27,0.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,378510,378475,510475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,378511,378475,511475,2021-01-01,0.08,0.08,0.2,0.39,0.16,0.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,378512,378475,512475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
data.shape

(302168, 65)

In [5]:
data.info() # 데이터 자료형 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302168 entries, 0 to 302167
Data columns (total 65 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   GRID_ID                     302168 non-null  int64
 1   GRID_X_AXIS                 302168 non-null  int64
 2   GRID_Y_AXIS                 302168 non-null  int64
 3   OCRN_YMD                    302168 non-null  object
 4   M00                         302168 non-null  float64
 5   M10                         302168 non-null  float64
 6   M15                         302168 non-null  float64
 7   M20                         302168 non-null  float64
 8   M25                         302168 non-null  float64
 9   M30                         302168 non-null  float64
 10  M35                         302168 non-null  float64
 11  M40                         302168 non-null  float64
 12  M45                         302168 non-null  float64
 13  M50                         302168 non-null  float64
 14  M55                         302168 non-null  float64
 15  M60                         302168 non-null  float64
 16  M65                         302168 non-null  float64
 17  M70                         302168 non-null  float64
 18  F00                         302168 non-null  float64
 19  F10                         302168 non-null  float64
 20  F15                         302168 non-null  float64
 21  F20                         302168 non-null  float64
 22  F25                         302168 non-null  float64
 23  F30                         302168 non-null  float64
 24  F35                         302168 non-null  float64
 25  F40                         302168 non-null  float64
 26  F45                         302168 non-null  float64
 27  F50                         302168 non-null  float64
 28  F55                         302168 non-null  float64
 29  F60                         302168 non-null  float64
 30  F65                         302168 non-null  float64
 31  F70                         302168 non-null  float64
 32  DONG_CD                     302168 non-null  int64
 33  DONG_NM                     302168 non-null  object
 34  HGTPOJ_ACDNT_OCRN_CNT       302168 non-null  float64
 35  PNTRINJ_OCRN_CNT            302168 non-null  float64
 36  MCHN_ACDNT_OCRN_CNT         302168 non-null  float64
 37  ETC_OCRN_CNT                302168 non-null  float64
 38  BLTRM_OCRN_CNT              302168 non-null  float64
 39  ACDNT_INJ_OCRN_CNT          302168 non-null  float64
 40  EXCL_DISEASE_OCRN_CNT       302168 non-null  float64
 41  VHC_ACDNT_OCRN_CNT          302168 non-null  float64
 42  HRFAF_OCRN_CNT              302168 non-null  float64
 43  AGRCMCHN_ACDNT_OCRN_CNT     302168 non-null  float64
 44  DRKNSTAT_OCRN_CNT           302168 non-null  float64
 45  ANML_INSCT_ACDNT_OCRN_CNT   302168 non-null  float64
 46  FLPS_ACDNT_OCRN_CNT         302168 non-null  float64
 47  UNKNWN_OCRN_CNT             302168 non-null  float64
 48  PDST_ACDNT_OCRN_CNT         302168 non-null  float64
 49  LACRTWND_OCRN_CNT           302168 non-null  float64
 50  MTRCYC_ACDNT_OCRN_CNT       302168 non-null  float64
 51  THML_DAMG_OCRN_CNT          302168 non-null  float64
 52  DRV_ACDNT_OCRN_CNT          302168 non-null  float64
 53  DRWNG_OCRN_CNT              302168 non-null  float64
 54  PRGNTW_ACDNT_OCRN_CNT       302168 non-null  float64
 55  BCYC_ACDNT_OCRN_CNT         302168 non-null  float64
 56  ELTRC_ACDNT_OCRN_CNT        302168 non-null  float64
 57  POSNG_OCRN_CNT              302168 non-null  float64
 58  ASPHYXIA_OCRN_CNT           302168 non-null  float64
 59  FALLING_OCRN_CNT            302168 non-null  float64
 60  FLAME_OCRN_CNT              302168 non-null  float64
 61  CHMC_SBSTNC_ACDNT_OCRN_CNT  302168 non-null  float64
 62  WETHR_ACDNT_OCRN_CNT        302168 non-null  float64
 63  SXAL_ASALT_OCRN_CNT         302168 non-null  float64
 64  BURN_OCRN_CNT               302168 non-null  float64
dtypes: float64(59), int64(4), object(2)
memory usage: 149.8+ MB

In [6]:
aa = data.loc[:,'M00':'F70']
aa

,M00,M10,M15,M20,M25,M30,M35,M40,M45,M50,...,F25,F30,F35,F40,F45,F50,F55,F60,F65,F70
0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
1,0.00,0.00,0.4,0.00,0.27,0.22,0.07,0.04,0.44,0.25,...,0.23,0.00,0.37,0.33,0.29,0.04,0.36,0.3,0.0,0.27
2,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
3,0.08,0.08,0.2,0.39,0.16,0.22,0.23,0.27,0.41,0.32,...,0.17,0.13,0.21,0.19,0.21,0.45,0.43,0.3,0.2,0.23
4,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302163,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
302164,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
302165,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
302166,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
302167,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00

In [7]:
FP = aa.sum(axis=1) # 유동인구 total
data["FP_DATA"] = FP
data

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT,FP_DATA
0,378508,378475,508475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
1,378509,378475,509475,2021-01-01,0.00,0.00,0.4,0.00,0.27,0.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.22
2,378510,378475,510475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
3,378511,378475,511475,2021-01-01,0.08,0.08,0.2,0.39,0.16,0.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.76
4,378512,378475,512475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302163,417521,417475,521475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
302164,418517,418475,517475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
302165,418518,418475,518475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
302166,418519,418475,519475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
302167,418520,418475,520475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00

In [8]:
total = data.loc[:,'HGTPOJ_ACDNT_OCRN_CNT':'BURN_OCRN_CNT'].sum(axis=1) # 사고 발생 total
data['total'] = total
data

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT,FP_DATA,total
0,378508,378475,508475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
1,378509,378475,509475,2021-01-01,0.00,0.00,0.4,0.00,0.27,0.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.22,0.0
2,378510,378475,510475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
3,378511,378475,511475,2021-01-01,0.08,0.08,0.2,0.39,0.16,0.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.76,0.0
4,378512,378475,512475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302163,417521,417475,521475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
302164,418517,418475,517475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
302165,418518,418475,518475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
302166,418519,418475,519475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
302167,418520,418475,520475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0

In [9]:
# total기준 정렬
# data.set_index('total',inplace=True)

In [11]:
data['OCRN_YMD'] = pd.to_datetime(data['OCRN_YMD'])

In [13]:
# 요일 정보 입력
data['week'] = data['OCRN_YMD'].dt.weekday
data

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT,FP_DATA,total,week
0,378508,378475,508475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,4
1,378509,378475,509475,2021-01-01,0.00,0.00,0.4,0.00,0.27,0.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.22,0.0,4
2,378510,378475,510475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,4
3,378511,378475,511475,2021-01-01,0.08,0.08,0.2,0.39,0.16,0.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.76,0.0,4
4,378512,378475,512475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302163,417521,417475,521475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,3
302164,418517,418475,517475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,3
302165,418518,418475,518475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,3
302166,418519,418475,519475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,3
302167,418520,418475,520475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,3